### ISSUE TITLE
Bug in published getting-started

### ISSUE THREAD

**Issue by sporksmith** [proptest-rs/proptest#251]
From https://altsysrq.github.io/proptest-book/proptest/getting-started.html:

```
#![allow(unused)]
fn main() {
fn parse_date(s: &str) -> Option<(u32, u32, u32)> {
...
```

This actually does compile, though not after the test is added, since `parse_date` isn't in scope.

It looks like the version in [source control](https://github.com/AltSysrq/proptest/blob/master/book/src/proptest/getting-started.md) doesn't have the `main` wrapper. Maybe the published book needs to be rebuilt, or is being built from some other source?

**Comment by matthew-russo** [comment]
This is caused by mdbook.

https://rust-lang.github.io/mdBook/format/mdbook.html#rust-playground

> If there is no main function, then the code is automatically wrapped inside one.

I've just added an empty main fn so one isn't generated. validated locally w/ `mdbook serve`

<img width="827" alt="Screenshot 2023-07-15 at 11 39 38 AM" src="https://github.com/proptest-rs/proptest/assets/22038728/aef2d946-445c-4a78-8027-320baa7360d2">
