### ISSUE TITLE
Is there a way to assert against previous value of function under test

### ISSUE THREAD

**Issue by atodorov** [proptest-rs/proptest#289]
Is there a way to model the below scenario using proptest ? 

```
                #[test]
                fn result_should_increase_when_argument_increases() {
                        let mut previous = -1.0

                        for i in 0..=1_000_000 {
                                let s = f64::from(i) * 0.000_001;
                                let result = function_under_test(s);

                                assert!(
                                        previous < result,
                                        "previous={previous:?}, result={result:?}, s={s:?}"
                                );
                                previous = result;
                        }
                }
```

I tried 

```
                use proptest::test_runner::TestRunner;

                #[test]
                fn with_proptest_result_should_increase_when_argument_increases() {
                        let mut previous = -1.0;

                        let mut runner = TestRunner::default();
                        runner.run(&(0.0f64..1.0f64), |s| {
                                let result = function_under_test(s);

                                assert!(
                                        previous < result,
                                        "previous={previous:?}, result={result:?}, s={s:?}"
                                );
                                previous = result;
                                Ok(())
                        });
                }
```

and I got ```error[E0594]: cannot assign to `previous`, as it is a captured variable in a `Fn` closure```

**Comment by rex-remind101** [comment]
First, your error is a compiler error from rust, because `run` takes an immutable `impl Fn`, not `FnMut`. I believe you can get around that by using `RefCell` or equivalent.

Second, using `(0.0f64..1.0f64)` uses a range sampler which looks like it is defined here https://github.com/proptest-rs/proptest/blob/master/proptest/src/num.rs#L63-L79 , and that uses `sample_uniform` which will sample uniformly over that range. What it sounds like you want is to iterate over a _strict total order_ of digits, which you demonstrate in your initial test. proptest is meant for randomly testing over an interface. _Maybe_ what you want is doable somehow, but it doesn't seem like the right use case to me, and in actuality I'd use a for-loop like you demonstrated.

**Comment by matthew-russo** [comment]
if you do want to test over arbitrarily generated inputs but have ordering, one option would be to generate `Vec`'s of your input and then sort them however you need them sorted. 

I'm going to close this as I don't think there's much else to be done. If you need any other help, please feel free to open a new issue
